### ISSUE TITLE
Use Minted for code highlighting

### ISSUE THREAD

**Issue by KilnOfTheSecondFlame** [taneher/HSLU#19]
In my opinion the [minted package](https://www.ctan.org/pkg/minted) is easier to use, and produces nicer results. However, it has a Python backend, so if you want to stay TeX-native this is of course not feasible.

lstlisting:
![image](https://user-images.githubusercontent.com/7289947/77334155-b7e96d00-6d24-11ea-802e-2f9bd85d1cd9.png)

minted:
![image](https://user-images.githubusercontent.com/7289947/77334198-c3d52f00-6d24-11ea-9803-f7e194a9f800.png)

**Comment by KilnOfTheSecondFlame** [comment]
Relevant [branch](https://github.com/gathurian/HSLU/tree/enh/use_minted)

**Comment by gathurian** [comment]
I think it can be assumed that Python is installed on pretty much every CompSci student that needs these summaries. Is it based on Python2 or 3?

However, what are the dependencies? i.e what/how many pip packages do have to be installed before being able to fully compile the documents? And how does it fare performance-wise compared to TeX-native?

**Comment by KilnOfTheSecondFlame** [comment]
It needs [Pygments](https://pypi.org/project/Pygments/), I think that package is available in 2 and 3, and the impact on building is negligible, aka I did not notice any drop in build speed (in my opinion).

**Comment by KilnOfTheSecondFlame** [comment]
Ok, after timing the build from source, I stand corrected

| Description | lstlisting | minted |
| :- | :-: | :-: |
|TotalSeconds | 2.737603 | 7.4229448 |
|TotalMilliseconds | 2737.603 | 7422.9448 |

PowerShell used:
```powershell
Measure-Command {
    pdflatex.exe -synctex=1 -shell-escape -interaction=nonstopmode C.tex
    pdflatex.exe -synctex=1 -shell-escape -interaction=nonstopmode C.tex
}
```

**Comment by gathurian** [comment]
Hm, roughly triple the time to compile and added dependencies for prettier code? Gotta say, I'm not a big fan of it. Of course you're free to use it on a feature-branch, but I'm not gonna merge it into master.

**Comment by KilnOfTheSecondFlame** [comment]
I mean its 5seconds of overhead. But your summary is small right now, this time will go up the longer it is, and then it will not be that much of a difference. But yeh, it's your repo :D
